// events and activities management system/frontend_angular/src/app/components/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './login.component.html'
})
export class LoginComponent {

  loginForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: [''],
      password: ['']
    });
  }

  login() {
    this.auth.login(this.loginForm.value).subscribe({
      next: (res) => {

        sessionStorage.setItem('token', res.token);

        if (res.role === 'student') this.router.navigate(['/student']);
        if (res.role === 'faculty') this.router.navigate(['/faculty']);
        if (res.role === 'admin') this.router.navigate(['/admin']);
      },

      error: (err) => {
        alert(err.error?.message || 'Login failed');
      }
    });
  }
}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-5 col-lg-4">

      <div class="card shadow-lg border-0 rounded-4">
        <div class="card-body p-4">

          <h3 class="text-center mb-4 fw-bold">
            College Event Management
          </h3>

          <form [formGroup]="loginForm">

            <div class="mb-3">
              <label class="form-label">Email</label>
              <input
                type="email"
                class="form-control"
                formControlName="email"
              />
            </div>

            <div class="mb-3">
              <label class="form-label">Password</label>
              <input
                type="password"
                class="form-control"
                formControlName="password"
              />
            </div>

            <button
              class="btn btn-primary w-100 mt-2"
              type="button"
              (click)="login()"
            >
              Login
            </button>

          </form>

          <p class="text-center mt-3 mb-0">
            Don’t have an account?
            <a routerLink="/register">Register</a>
          </p>

        </div>
      </div>

    </div>
  </div>
</div>

// events and activities management system/frontend/src/comp/Login.jsx
import { useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const login = async () => {
    try {
      const res = await axios.post(
        "http://localhost:5000/api/auth/login",
        { email, password }
      );

      sessionStorage.setItem("token", res.data.token);

      if (res.data.role === "student") window.location.href = "/student";
      if (res.data.role === "faculty") window.location.href = "/faculty";
      if (res.data.role === "admin") window.location.href = "/admin";

    } catch (err) {
      alert(err.response?.data?.message || "Login failed");
    }
  };

  return (
  
    <div className="container mt-5">
      <div className="row justify-content-center">
        <div className="col-md-5 col-lg-4">

          <div className="card shadow-lg border-0 rounded-4">
            <div className="card-body p-4">

              <h3 className="text-center mb-4 fw-bold">
                College Event Management
              </h3>

              <div className="mb-3">
                <label className="form-label">Email</label>
                <input
                  type="email"
                  className="form-control"
                  placeholder="Enter email"
                  onChange={e => setEmail(e.target.value)}
                />
              </div>

              <div className="mb-3">
                <label className="form-label">Password</label>
                <input
                  type="password"
                  className="form-control"
                  placeholder="Enter password"
                  onChange={e => setPassword(e.target.value)}
                />
              </div>

              <button
                className="btn btn-primary w-100 mt-2"
                onClick={login}
              >
                Login
              </button>

              <p className="text-center mt-3 mb-0">
                Don’t have an account?{" "}
                <Link to="/register" className="text-decoration-none">
                  Register
                </Link>
              </p>

            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
